apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
---
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit
type: Opaque
data:
  S3_BUCKET_NAME: s3-secrets
  AWS_ACCESS_KEY_ID: id
  AWS_SECRET_ACCESS_KEY: secret
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: fluent-bit
spec:
  chart: fluent-bit
  repo: https://fluent.github.io/helm-charts
  version: 0.42.0
  valuesContent: |
    envFrom:
    - secretRef:
      - name: fluent-bit

    config:
      service: |
        [SERVICE]
            Flush        1
            Log_Level    info
            HTTP_Server  On
            HTTP_Listen  0.0.0.0
            HTTP_Port    2020

      customParsers: |
        [PARSER]
            Name        json-parser
            Format      json
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%SZ
            Time_Keep   On

      inputs: |
        [INPUT]
            Name              tail
            Tag               worker-logs
            Path              /var/log/worker/*.log
            Parser            json-parser
            Mem_Buf_Limit     100MB
            Skip_Long_Lines   Off
            Refresh_Interval  5

      outputs: |
        [OUTPUT]
            Name            s3
            Bucket          ${S3_BUCKET_NAME}
            Match           worker-logs
            Use_Put_Object  On
            Total_File_Size 1M
            Upload_Timeout  1m
        

    volumeMounts:
      - name: config
        mountPath: /fluent-bit/etc/conf

    daemonSetVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    daemonSetVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true