apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: logging
spec:
  chart: loki
  repo: https://grafana.github.io/helm-charts
  version: 5.41.8
  valuesContent: |
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1