# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: taskqueue.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import AsyncGenerator

import betterproto
import grpclib


@dataclass
class TaskQueuePutRequest(betterproto.Message):
    stub_id: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)


@dataclass
class TaskQueuePutResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    task_id: str = betterproto.string_field(2)


@dataclass
class TaskQueuePopRequest(betterproto.Message):
    stub_id: str = betterproto.string_field(1)
    container_id: str = betterproto.string_field(2)


@dataclass
class TaskQueuePopResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    task_msg: bytes = betterproto.bytes_field(2)


@dataclass
class TaskQueueLengthRequest(betterproto.Message):
    stub_id: str = betterproto.string_field(1)


@dataclass
class TaskQueueLengthResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    length: int = betterproto.int64_field(2)


@dataclass
class TaskQueueCompleteRequest(betterproto.Message):
    task_id: str = betterproto.string_field(1)
    stub_id: str = betterproto.string_field(2)
    task_duration: float = betterproto.float_field(3)
    task_status: str = betterproto.string_field(4)
    container_id: str = betterproto.string_field(5)
    container_hostname: str = betterproto.string_field(6)
    keep_warm_seconds: float = betterproto.float_field(7)


@dataclass
class TaskQueueCompleteResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)


@dataclass
class TaskQueueMonitorRequest(betterproto.Message):
    task_id: str = betterproto.string_field(1)
    stub_id: str = betterproto.string_field(2)
    container_id: str = betterproto.string_field(3)


@dataclass
class TaskQueueMonitorResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    cancelled: bool = betterproto.bool_field(2)
    complete: bool = betterproto.bool_field(3)
    timed_out: bool = betterproto.bool_field(4)


class TaskQueueServiceStub(betterproto.ServiceStub):
    async def task_queue_put(
        self, *, stub_id: str = "", payload: bytes = b""
    ) -> TaskQueuePutResponse:
        request = TaskQueuePutRequest()
        request.stub_id = stub_id
        request.payload = payload

        return await self._unary_unary(
            "/taskqueue.TaskQueueService/TaskQueuePut",
            request,
            TaskQueuePutResponse,
        )

    async def task_queue_pop(
        self, *, stub_id: str = "", container_id: str = ""
    ) -> TaskQueuePopResponse:
        request = TaskQueuePopRequest()
        request.stub_id = stub_id
        request.container_id = container_id

        return await self._unary_unary(
            "/taskqueue.TaskQueueService/TaskQueuePop",
            request,
            TaskQueuePopResponse,
        )

    async def task_queue_monitor(
        self, *, task_id: str = "", stub_id: str = "", container_id: str = ""
    ) -> AsyncGenerator[TaskQueueMonitorResponse, None]:
        request = TaskQueueMonitorRequest()
        request.task_id = task_id
        request.stub_id = stub_id
        request.container_id = container_id

        async for response in self._unary_stream(
            "/taskqueue.TaskQueueService/TaskQueueMonitor",
            request,
            TaskQueueMonitorResponse,
        ):
            yield response

    async def task_queue_complete(
        self,
        *,
        task_id: str = "",
        stub_id: str = "",
        task_duration: float = 0,
        task_status: str = "",
        container_id: str = "",
        container_hostname: str = "",
        keep_warm_seconds: float = 0,
    ) -> TaskQueueCompleteResponse:
        request = TaskQueueCompleteRequest()
        request.task_id = task_id
        request.stub_id = stub_id
        request.task_duration = task_duration
        request.task_status = task_status
        request.container_id = container_id
        request.container_hostname = container_hostname
        request.keep_warm_seconds = keep_warm_seconds

        return await self._unary_unary(
            "/taskqueue.TaskQueueService/TaskQueueComplete",
            request,
            TaskQueueCompleteResponse,
        )

    async def task_queue_length(self, *, stub_id: str = "") -> TaskQueueLengthResponse:
        request = TaskQueueLengthRequest()
        request.stub_id = stub_id

        return await self._unary_unary(
            "/taskqueue.TaskQueueService/TaskQueueLength",
            request,
            TaskQueueLengthResponse,
        )
