# fly.toml app configuration file generated for control-plane-postgres on 2024-11-19T13:50:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'control-plane-postgres'
primary_region = 'lax'

[build]
  image = 'postgres'

[env]
  PRIMARY_REGION = 'lax'

[[mounts]]
  source = 'pg_data'
  destination = '/bitnami/postgresql'

[[services]]
  protocol = 'tcp'
  internal_port = 5432
  auto_start_machines = false

  [[services.ports]]
    port = 5432
    handlers = ['pg_tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[files]]
  guest_path = '/opt/bitnami/postgresql/conf/pg_hba.conf'
  local_path = './pg_hba.conf'

[[files]]
  guest_path = '/opt/bitnami/postgresql/conf/postgresql.conf'
  local_path = './postgresql.conf'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9187
  path = '/metrics'
  https = false
