# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: tailscale
# type: Opaque
# stringData:
#   TS_ACCEPT_DNS: ""
#   TS_AUTHKEY: ""
#   TS_EXTRA_ARGS: ""
#   TS_KUBE_SECRET: ""
#   TS_TAILSCALED_EXTRA_ARGS: ""
#   TS_USERSPACE: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale
  namespace: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: tailscale
        image: ghcr.io/tailscale/tailscale:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: tailscale
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/ash
              - -c
              - |
                tailscale --socket=/tmp/tailscaled.sock logout
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
