# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: webserver.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class WebserverRequestRequest(betterproto.Message):
    stub_id: str = betterproto.string_field(1)
    method: str = betterproto.string_field(2)
    path: str = betterproto.string_field(3)
    headers: bytes = betterproto.bytes_field(4)
    payload: bytes = betterproto.bytes_field(5)


@dataclass
class WebserverRequestResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    response: bytes = betterproto.bytes_field(2)


class WebserverServiceStub(betterproto.ServiceStub):
    async def webserver_request(
        self,
        *,
        stub_id: str = "",
        method: str = "",
        path: str = "",
        headers: bytes = b"",
        payload: bytes = b"",
    ) -> WebserverRequestResponse:
        request = WebserverRequestRequest()
        request.stub_id = stub_id
        request.method = method
        request.path = path
        request.headers = headers
        request.payload = payload

        return await self._unary_unary(
            "/webserver.WebserverService/WebserverRequest",
            request,
            WebserverRequestResponse,
        )
