---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: beta9
image: docker.io/rancher/k3s:v1.28.5-k3s1
servers: 1

ports:
- port: 1993:80
  nodeFilters:
  - loadbalancer

volumes:
- volume: $PWD/manifests:k3s-manifests-custom
  nodeFilters:
  - server:0
- volume: $PWD/.k3d/storage:k3s-storage
  nodeFilters:
  - servers:*

registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5001"
    volumes:
    - $PWD/.k3d/registry:/var/lib/registry

options:
  k3d:
    wait: true
    timeout: "60s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
