syntax = "proto3";

option go_package = "github.com/beam-cloud/beta9/proto";
import "google/protobuf/timestamp.proto";

package disk;

import "google/api/annotations.proto";

service DiskService {
  rpc GetOrCreateDisk(GetOrCreateDiskRequest) returns (GetOrCreateDiskResponse) {
    option (google.api.http) = {
      post: "/disks"
      body: "*"
    };
  }
  rpc ListDisks(ListDisksRequest) returns (ListDisksResponse) {
    option (google.api.http) = {
      get: "/disks"
    };
  }
  rpc DeleteDisk(DeleteDiskRequest) returns (DeleteDiskResponse) {
    option (google.api.http) = {
      post: "/disks/{name}/delete"
      body: "*"
    };
  }
}

message DiskInstance {
  string id = 1;
  string name = 2;
  string size = 3;
  string mount_path = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
  string workspace_id = 7;
  string workspace_name = 8;
}

message GetOrCreateDiskRequest {
  string name = 1;
  string size = 2;
  string mount_path = 3;
}

message GetOrCreateDiskResponse {
  bool ok = 1;
  string err_msg = 2;
  DiskInstance disk = 3;
}

message ListDisksRequest {}

message ListDisksResponse {
  bool ok = 1;
  string err_msg = 2;
  repeated DiskInstance disks = 3;
}

message DeleteDiskRequest {
  string name = 1;
}

message DeleteDiskResponse {
  bool ok = 1;
  string err_msg = 2;
}
