apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: localstack
  namespace: beta9
spec:
  repo: https://localstack.github.io/helm-charts
  chart: localstack
  createNamespace: false
  version: 0.6.5
  valuesContent: |-
    extraEnvVars:
    - name: SERVICES
      value: "s3"
    enableStartupScripts: true
    startupScriptContent: |
      #!/bin/bash
      awslocal s3 mb s3://juicefs
      awslocal s3 mb s3://logs
      awslocal s3 mb s3://beta9-images
    persistence:
      enabled: true
      storageClass: local-path
      accessModes:
      - ReadWriteOnce
      size: 50Gi
