package types

const (
	DefaultAgentName                = "agent"
	DefaultAgentServiceName         = "beam-agent"
	DefaultAgentServiceDescription  = "Beam Agent"
	DefaultAgentBinaryPath          = "/usr/local/bin/beam-agent"
	DefaultAgentBinaryPattern       = "/usr/local/bin/beam-agent-%s-%s"
	DefaultAgentStateDir            = "/var/lib/beam/agent"
	DefaultAgentServiceManager      = "auto"
	AgentServiceManagerSystemd      = "systemd"
	AgentServiceManagerLaunchd      = "launchd"
	AgentServiceManagerNone         = "none"
	AgentServiceUnitExtension       = ".service"
	AgentSystemdNetworkOnlineTarget = "network-online.target"
	AgentSystemdDockerService       = "docker.service"
	AgentSystemdUnitDir             = "/etc/systemd/system"
	AgentSystemdRuntimeDir          = "/run/systemd/system"
	AgentLaunchdUserDir             = "Library/LaunchAgents"
	AgentLaunchdSystemDir           = "/Library/LaunchDaemons"
	AgentLaunchdLabel               = "dev.beam.agent"
	AgentLaunchdPlistExtension      = ".plist"
	AgentLaunchdSystemDomain        = "system"
	AgentLaunchdUserDomainPrefix    = "gui/"
	AgentSystemctlCommand           = "systemctl"
	AgentLaunchctlCommand           = "launchctl"
	AgentPathEnv                    = "PATH"
	AgentServiceDefaultPath         = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
	AgentServiceLogFile             = "agent.log"
	AgentServiceErrorLogFile        = "agent.err.log"
	AgentRegistryAddr               = "127.0.0.1:5000"
	AgentWorkerEntrypoint           = "/usr/local/bin/worker"
	AgentTmpSizeLimit               = "30Gi"
	AgentStateDirName               = "agent"
	AgentLockFileName               = "agent.lock"
	AgentJoinTokenFileName          = "join-token"
	AgentRuntimeStateFileName       = "agent-state.json"
	BeamStateDirName                = "beam"
	LoopbackHost                    = "127.0.0.1"
	HostnameEnv                     = "HOSTNAME"
	PodNameEnv                      = "POD_NAME"
	GatewayTSNetHostnameEnv         = "BETA9_GATEWAY_TSNET_HOSTNAME"
	CacheCoordinatorTokenEnv        = "CACHE_COORDINATOR_TOKEN"
	NvidiaVisibleDevicesAll         = "all"
	NvidiaVisibleDevicesEnv         = "NVIDIA_VISIBLE_DEVICES"
	AgentDockerHostsEnv             = "BEAM_AGENT_DOCKER_HOST_ALIASES"
	AgentInContainerEnv             = "BEAM_AGENT_CONTAINER"
	AgentHostnameEnv                = "BEAM_AGENT_HOSTNAME"
	AgentRegistryForwardEnv         = "BEAM_AGENT_LOCAL_REGISTRY_FORWARD"
	AgentTargetHostEnv              = "BEAM_AGENT_LOCAL_TARGET_HOST"
	AgentFingerprintEnv             = "BEAM_AGENT_MACHINE_FINGERPRINT"
	AgentStateDirEnv                = "BEAM_AGENT_STATE_DIR"
	AgentBinaryPathEnv              = "BEAM_AGENT_BIN_PATH"
	AgentSourceDirEnv               = "BEAM_AGENT_SOURCE_DIR"
	AgentBuildCacheDirEnv           = "BEAM_AGENT_BUILD_CACHE_DIR"
	AgentWorkerImageEnv             = "BEAM_WORKER_IMAGE"
	AgentDownloadURLEnv             = "BEAM_AGENT_URL"
	AgentInstallDockerEnv           = "BEAM_AGENT_INSTALL_DOCKER"
	AgentStorageModeEnv             = "BEAM_AGENT_WORKSPACE_STORAGE_MODE"
	AgentWorkerPlatformEnv          = "BEAM_AGENT_WORKER_PLATFORM"
	AgentVerboseEnv                 = "BEAM_AGENT_VERBOSE"
	AgentNoColorEnv                 = "NO_COLOR"
	AgentGatewayURLEnv              = "BEAM_GATEWAY_HTTP_URL"
	AgentImagesPath                 = "/images"
	AgentImageCachePath             = "/images/cache"
	AgentImageMountPattern          = "/images/mnt/%s"
	AgentTmpPath                    = "/tmp"
	AgentDataPath                   = "/data"
	AgentWorkspacePath              = "/workspace/data"
	AgentCachePath                  = "/var/lib/beta9/cache"
	AgentCheckpointPath             = "/checkpoints"
	AgentLogsPath                   = "/var/log/worker"
	AgentConfigPath                 = "/etc/beam/agent-worker.json"
	AgentCacheFSMountPath           = "/cache"
	HostKubeletDevicePluginsPath    = "/var/lib/kubelet/device-plugins"
	HostKubeletDeviceCheckpointPath = "/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint"
	HostNetnsPath                   = "/var/run/netns"
	HostCgroupPath                  = "/sys/fs/cgroup"
	HostFuseDevicePath              = "/dev/fuse"
	AgentDockerLabelManaged         = "dev.beam.agent.worker"
	AgentDockerLabelWorkerID        = "dev.beam.agent.worker_id"
	AgentDockerLabelMachineID       = "dev.beam.agent.machine_id"
	AgentDockerLabelPoolName        = "dev.beam.agent.pool_name"
	AgentTelemetrySourceAgent       = "agent"
	AgentTelemetrySourceWorker      = "worker"
	AgentMachineStatusSchedulable   = "schedulable"
	AgentMachineStatusDisconnected  = "disconnected"
	AgentMachineStatusPreflightFail = "preflight_failed"
)

const (
	WorkerConfigPathEnv       = "CONFIG_PATH"
	WorkerConfigJSONEnv       = "CONFIG_JSON"
	WorkerIDEnv               = "WORKER_ID"
	WorkerTokenEnv            = "WORKER_TOKEN"
	WorkerPoolEnv             = "WORKER_POOL_NAME"
	WorkerMachineEnv          = "WORKER_MACHINE_ID"
	WorkerPersistentEnv       = "WORKER_PERSISTENT"
	WorkerRouteTransportEnv   = "WORKER_ROUTE_TRANSPORT"
	WorkerRouteTargetEnv      = "WORKER_ROUTE_LOCAL_TARGET_HOST"
	WorkerCPUEnv              = "CPU_LIMIT"
	WorkerMemoryEnv           = "MEMORY_LIMIT"
	WorkerGPUEnv              = "GPU_TYPE"
	WorkerGPUCountEnv         = "GPU_COUNT"
	WorkerPodHostEnv          = "POD_HOSTNAME"
	WorkerPodIPEnv            = "POD_IP"
	WorkerPodUIDEnv           = "POD_UID"
	WorkerHostnameEnv         = HostnameEnv
	WorkerNetworkPrefixEnv    = "NETWORK_PREFIX"
	WorkerDefaultInterfaceEnv = "WORKER_DEFAULT_INTERFACE"
	WorkerIptablesModeEnv     = "WORKER_IPTABLES_MODE"
	WorkerStartConcurrencyEnv = "WORKER_CONTAINER_START_CONCURRENCY"
	WorkerNetworkSlotsEnv     = "CONTAINER_NETWORK_SLOT_POOL_SIZE"
	WorkerMinimalConfigEnv    = "BEAM_WORKER_MINIMAL_CONFIG"

	ContainerGatewayGRPCHostEnv = "BETA9_GATEWAY_HOST"
	ContainerGatewayGRPCPortEnv = "BETA9_GATEWAY_PORT"
	ContainerGatewayHTTPHostEnv = "BETA9_GATEWAY_HOST_HTTP"
	ContainerGatewayHTTPPortEnv = "BETA9_GATEWAY_PORT_HTTP"
	ContainerHostnameEnv        = "CONTAINER_HOSTNAME"
)

const (
	CacheLocalityEnv    = "CACHE_LOCALITY"
	CacheNodeEnv        = "CACHE_NODE_ID"
	CacheHostNetworkEnv = "CACHE_HOST_NETWORK"
	CacheServerOnlyEnv  = "CACHE_SERVER_ONLY"
	CacheServerPortEnv  = "CACHE_SERVER_PORT"
)

const (
	PrivatePoolFallbackInternal = "internal"
	PrivatePoolFallbackWait     = "wait"
	PrivatePoolFallbackFail     = "fail"
)
