// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WebEndpointService_WebEndpointServe_FullMethodName = "/endpoint.WebEndpointService/WebEndpointServe"
)

// WebEndpointServiceClient is the client API for WebEndpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebEndpointServiceClient interface {
	WebEndpointServe(ctx context.Context, in *WebEndpointServeRequest, opts ...grpc.CallOption) (*WebEndpointServeResponse, error)
}

type webEndpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebEndpointServiceClient(cc grpc.ClientConnInterface) WebEndpointServiceClient {
	return &webEndpointServiceClient{cc}
}

func (c *webEndpointServiceClient) WebEndpointServe(ctx context.Context, in *WebEndpointServeRequest, opts ...grpc.CallOption) (*WebEndpointServeResponse, error) {
	out := new(WebEndpointServeResponse)
	err := c.cc.Invoke(ctx, WebEndpointService_WebEndpointServe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebEndpointServiceServer is the server API for WebEndpointService service.
// All implementations must embed UnimplementedWebEndpointServiceServer
// for forward compatibility
type WebEndpointServiceServer interface {
	WebEndpointServe(context.Context, *WebEndpointServeRequest) (*WebEndpointServeResponse, error)
	mustEmbedUnimplementedWebEndpointServiceServer()
}

// UnimplementedWebEndpointServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWebEndpointServiceServer struct {
}

func (UnimplementedWebEndpointServiceServer) WebEndpointServe(context.Context, *WebEndpointServeRequest) (*WebEndpointServeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebEndpointServe not implemented")
}
func (UnimplementedWebEndpointServiceServer) mustEmbedUnimplementedWebEndpointServiceServer() {}

// UnsafeWebEndpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebEndpointServiceServer will
// result in compilation errors.
type UnsafeWebEndpointServiceServer interface {
	mustEmbedUnimplementedWebEndpointServiceServer()
}

func RegisterWebEndpointServiceServer(s grpc.ServiceRegistrar, srv WebEndpointServiceServer) {
	s.RegisterService(&WebEndpointService_ServiceDesc, srv)
}

func _WebEndpointService_WebEndpointServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebEndpointServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebEndpointServiceServer).WebEndpointServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebEndpointService_WebEndpointServe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebEndpointServiceServer).WebEndpointServe(ctx, req.(*WebEndpointServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebEndpointService_ServiceDesc is the grpc.ServiceDesc for WebEndpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebEndpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endpoint.WebEndpointService",
	HandlerType: (*WebEndpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WebEndpointServe",
			Handler:    _WebEndpointService_WebEndpointServe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "endpoint.proto",
}
