// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EndpointService_StartEndpointServe_FullMethodName     = "/endpoint.EndpointService/StartEndpointServe"
	EndpointService_StopEndpointServe_FullMethodName      = "/endpoint.EndpointService/StopEndpointServe"
	EndpointService_EndpointServeKeepAlive_FullMethodName = "/endpoint.EndpointService/EndpointServeKeepAlive"
)

// EndpointServiceClient is the client API for EndpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointServiceClient interface {
	StartEndpointServe(ctx context.Context, in *StartEndpointServeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartEndpointServeResponse], error)
	StopEndpointServe(ctx context.Context, in *StopEndpointServeRequest, opts ...grpc.CallOption) (*StopEndpointServeResponse, error)
	EndpointServeKeepAlive(ctx context.Context, in *EndpointServeKeepAliveRequest, opts ...grpc.CallOption) (*EndpointServeKeepAliveResponse, error)
}

type endpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointServiceClient(cc grpc.ClientConnInterface) EndpointServiceClient {
	return &endpointServiceClient{cc}
}

func (c *endpointServiceClient) StartEndpointServe(ctx context.Context, in *StartEndpointServeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartEndpointServeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[0], EndpointService_StartEndpointServe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartEndpointServeRequest, StartEndpointServeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_StartEndpointServeClient = grpc.ServerStreamingClient[StartEndpointServeResponse]

func (c *endpointServiceClient) StopEndpointServe(ctx context.Context, in *StopEndpointServeRequest, opts ...grpc.CallOption) (*StopEndpointServeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopEndpointServeResponse)
	err := c.cc.Invoke(ctx, EndpointService_StopEndpointServe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) EndpointServeKeepAlive(ctx context.Context, in *EndpointServeKeepAliveRequest, opts ...grpc.CallOption) (*EndpointServeKeepAliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndpointServeKeepAliveResponse)
	err := c.cc.Invoke(ctx, EndpointService_EndpointServeKeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointServiceServer is the server API for EndpointService service.
// All implementations must embed UnimplementedEndpointServiceServer
// for forward compatibility.
type EndpointServiceServer interface {
	StartEndpointServe(*StartEndpointServeRequest, grpc.ServerStreamingServer[StartEndpointServeResponse]) error
	StopEndpointServe(context.Context, *StopEndpointServeRequest) (*StopEndpointServeResponse, error)
	EndpointServeKeepAlive(context.Context, *EndpointServeKeepAliveRequest) (*EndpointServeKeepAliveResponse, error)
	mustEmbedUnimplementedEndpointServiceServer()
}

// UnimplementedEndpointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndpointServiceServer struct{}

func (UnimplementedEndpointServiceServer) StartEndpointServe(*StartEndpointServeRequest, grpc.ServerStreamingServer[StartEndpointServeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StartEndpointServe not implemented")
}
func (UnimplementedEndpointServiceServer) StopEndpointServe(context.Context, *StopEndpointServeRequest) (*StopEndpointServeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopEndpointServe not implemented")
}
func (UnimplementedEndpointServiceServer) EndpointServeKeepAlive(context.Context, *EndpointServeKeepAliveRequest) (*EndpointServeKeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndpointServeKeepAlive not implemented")
}
func (UnimplementedEndpointServiceServer) mustEmbedUnimplementedEndpointServiceServer() {}
func (UnimplementedEndpointServiceServer) testEmbeddedByValue()                         {}

// UnsafeEndpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServiceServer will
// result in compilation errors.
type UnsafeEndpointServiceServer interface {
	mustEmbedUnimplementedEndpointServiceServer()
}

func RegisterEndpointServiceServer(s grpc.ServiceRegistrar, srv EndpointServiceServer) {
	// If the following call pancis, it indicates UnimplementedEndpointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EndpointService_ServiceDesc, srv)
}

func _EndpointService_StartEndpointServe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartEndpointServeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EndpointServiceServer).StartEndpointServe(m, &grpc.GenericServerStream[StartEndpointServeRequest, StartEndpointServeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_StartEndpointServeServer = grpc.ServerStreamingServer[StartEndpointServeResponse]

func _EndpointService_StopEndpointServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopEndpointServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).StopEndpointServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_StopEndpointServe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).StopEndpointServe(ctx, req.(*StopEndpointServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_EndpointServeKeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointServeKeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).EndpointServeKeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_EndpointServeKeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).EndpointServeKeepAlive(ctx, req.(*EndpointServeKeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndpointService_ServiceDesc is the grpc.ServiceDesc for EndpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endpoint.EndpointService",
	HandlerType: (*EndpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopEndpointServe",
			Handler:    _EndpointService_StopEndpointServe_Handler,
		},
		{
			MethodName: "EndpointServeKeepAlive",
			Handler:    _EndpointService_EndpointServeKeepAlive_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartEndpointServe",
			Handler:       _EndpointService_StartEndpointServe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "endpoint.proto",
}
