// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	VerifyBuild(ctx context.Context, in *VerifyImageBuildRequest, opts ...grpc.CallOption) (*VerifyImageBuildResponse, error)
	Build(ctx context.Context, in *ImageBuildRequest, opts ...grpc.CallOption) (GatewayService_BuildClient, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) VerifyBuild(ctx context.Context, in *VerifyImageBuildRequest, opts ...grpc.CallOption) (*VerifyImageBuildResponse, error) {
	out := new(VerifyImageBuildResponse)
	err := c.cc.Invoke(ctx, "/gateway.GatewayService/VerifyBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Build(ctx context.Context, in *ImageBuildRequest, opts ...grpc.CallOption) (GatewayService_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], "/gateway.GatewayService/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayServiceBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GatewayService_BuildClient interface {
	Recv() (*ImageBuildResponse, error)
	grpc.ClientStream
}

type gatewayServiceBuildClient struct {
	grpc.ClientStream
}

func (x *gatewayServiceBuildClient) Recv() (*ImageBuildResponse, error) {
	m := new(ImageBuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility
type GatewayServiceServer interface {
	VerifyBuild(context.Context, *VerifyImageBuildRequest) (*VerifyImageBuildResponse, error)
	Build(*ImageBuildRequest, GatewayService_BuildServer) error
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (UnimplementedGatewayServiceServer) VerifyBuild(context.Context, *VerifyImageBuildRequest) (*VerifyImageBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBuild not implemented")
}
func (UnimplementedGatewayServiceServer) Build(*ImageBuildRequest, GatewayService_BuildServer) error {
	return status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_VerifyBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyImageBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).VerifyBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.GatewayService/VerifyBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).VerifyBuild(ctx, req.(*VerifyImageBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageBuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).Build(m, &gatewayServiceBuildServer{stream})
}

type GatewayService_BuildServer interface {
	Send(*ImageBuildResponse) error
	grpc.ServerStream
}

type gatewayServiceBuildServer struct {
	grpc.ServerStream
}

func (x *gatewayServiceBuildServer) Send(m *ImageBuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyBuild",
			Handler:    _GatewayService_VerifyBuild_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _GatewayService_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
