// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: managedendpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EndpointHarnessService_Register_FullMethodName      = "/managedendpoint.EndpointHarnessService/Register"
	EndpointHarnessService_WatchConfig_FullMethodName   = "/managedendpoint.EndpointHarnessService/WatchConfig"
	EndpointHarnessService_AckConfig_FullMethodName     = "/managedendpoint.EndpointHarnessService/AckConfig"
	EndpointHarnessService_Heartbeat_FullMethodName     = "/managedendpoint.EndpointHarnessService/Heartbeat"
	EndpointHarnessService_PublishEvents_FullMethodName = "/managedendpoint.EndpointHarnessService/PublishEvents"
)

// EndpointHarnessServiceClient is the client API for EndpointHarnessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointHarnessServiceClient interface {
	// Register announces a replica's harness and returns its identity and the
	// current config revision. Idempotent per container.
	Register(ctx context.Context, in *HarnessRegisterRequest, opts ...grpc.CallOption) (*HarnessRegisterResponse, error)
	// WatchConfig streams config revisions targeted at the replica (fleet or
	// replica scoped). The first message is the current revision.
	WatchConfig(ctx context.Context, in *HarnessWatchConfigRequest, opts ...grpc.CallOption) (EndpointHarnessService_WatchConfigClient, error)
	// AckConfig reports whether a revision was applied.
	AckConfig(ctx context.Context, in *HarnessAckConfigRequest, opts ...grpc.CallOption) (*HarnessAckConfigResponse, error)
	// Heartbeat reports liveness, capacity and engine metrics.
	Heartbeat(ctx context.Context, in *HarnessHeartbeatRequest, opts ...grpc.CallOption) (*HarnessHeartbeatResponse, error)
	// PublishEvents forwards engine-side events into the platform event stream.
	PublishEvents(ctx context.Context, in *HarnessPublishEventsRequest, opts ...grpc.CallOption) (*HarnessPublishEventsResponse, error)
}

type endpointHarnessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointHarnessServiceClient(cc grpc.ClientConnInterface) EndpointHarnessServiceClient {
	return &endpointHarnessServiceClient{cc}
}

func (c *endpointHarnessServiceClient) Register(ctx context.Context, in *HarnessRegisterRequest, opts ...grpc.CallOption) (*HarnessRegisterResponse, error) {
	out := new(HarnessRegisterResponse)
	err := c.cc.Invoke(ctx, EndpointHarnessService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointHarnessServiceClient) WatchConfig(ctx context.Context, in *HarnessWatchConfigRequest, opts ...grpc.CallOption) (EndpointHarnessService_WatchConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &EndpointHarnessService_ServiceDesc.Streams[0], EndpointHarnessService_WatchConfig_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointHarnessServiceWatchConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EndpointHarnessService_WatchConfigClient interface {
	Recv() (*ConfigRevision, error)
	grpc.ClientStream
}

type endpointHarnessServiceWatchConfigClient struct {
	grpc.ClientStream
}

func (x *endpointHarnessServiceWatchConfigClient) Recv() (*ConfigRevision, error) {
	m := new(ConfigRevision)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *endpointHarnessServiceClient) AckConfig(ctx context.Context, in *HarnessAckConfigRequest, opts ...grpc.CallOption) (*HarnessAckConfigResponse, error) {
	out := new(HarnessAckConfigResponse)
	err := c.cc.Invoke(ctx, EndpointHarnessService_AckConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointHarnessServiceClient) Heartbeat(ctx context.Context, in *HarnessHeartbeatRequest, opts ...grpc.CallOption) (*HarnessHeartbeatResponse, error) {
	out := new(HarnessHeartbeatResponse)
	err := c.cc.Invoke(ctx, EndpointHarnessService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointHarnessServiceClient) PublishEvents(ctx context.Context, in *HarnessPublishEventsRequest, opts ...grpc.CallOption) (*HarnessPublishEventsResponse, error) {
	out := new(HarnessPublishEventsResponse)
	err := c.cc.Invoke(ctx, EndpointHarnessService_PublishEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointHarnessServiceServer is the server API for EndpointHarnessService service.
// All implementations must embed UnimplementedEndpointHarnessServiceServer
// for forward compatibility
type EndpointHarnessServiceServer interface {
	// Register announces a replica's harness and returns its identity and the
	// current config revision. Idempotent per container.
	Register(context.Context, *HarnessRegisterRequest) (*HarnessRegisterResponse, error)
	// WatchConfig streams config revisions targeted at the replica (fleet or
	// replica scoped). The first message is the current revision.
	WatchConfig(*HarnessWatchConfigRequest, EndpointHarnessService_WatchConfigServer) error
	// AckConfig reports whether a revision was applied.
	AckConfig(context.Context, *HarnessAckConfigRequest) (*HarnessAckConfigResponse, error)
	// Heartbeat reports liveness, capacity and engine metrics.
	Heartbeat(context.Context, *HarnessHeartbeatRequest) (*HarnessHeartbeatResponse, error)
	// PublishEvents forwards engine-side events into the platform event stream.
	PublishEvents(context.Context, *HarnessPublishEventsRequest) (*HarnessPublishEventsResponse, error)
	mustEmbedUnimplementedEndpointHarnessServiceServer()
}

// UnimplementedEndpointHarnessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEndpointHarnessServiceServer struct {
}

func (UnimplementedEndpointHarnessServiceServer) Register(context.Context, *HarnessRegisterRequest) (*HarnessRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEndpointHarnessServiceServer) WatchConfig(*HarnessWatchConfigRequest, EndpointHarnessService_WatchConfigServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchConfig not implemented")
}
func (UnimplementedEndpointHarnessServiceServer) AckConfig(context.Context, *HarnessAckConfigRequest) (*HarnessAckConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckConfig not implemented")
}
func (UnimplementedEndpointHarnessServiceServer) Heartbeat(context.Context, *HarnessHeartbeatRequest) (*HarnessHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEndpointHarnessServiceServer) PublishEvents(context.Context, *HarnessPublishEventsRequest) (*HarnessPublishEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishEvents not implemented")
}
func (UnimplementedEndpointHarnessServiceServer) mustEmbedUnimplementedEndpointHarnessServiceServer() {
}

// UnsafeEndpointHarnessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointHarnessServiceServer will
// result in compilation errors.
type UnsafeEndpointHarnessServiceServer interface {
	mustEmbedUnimplementedEndpointHarnessServiceServer()
}

func RegisterEndpointHarnessServiceServer(s grpc.ServiceRegistrar, srv EndpointHarnessServiceServer) {
	s.RegisterService(&EndpointHarnessService_ServiceDesc, srv)
}

func _EndpointHarnessService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HarnessRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointHarnessServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointHarnessService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointHarnessServiceServer).Register(ctx, req.(*HarnessRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointHarnessService_WatchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HarnessWatchConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EndpointHarnessServiceServer).WatchConfig(m, &endpointHarnessServiceWatchConfigServer{stream})
}

type EndpointHarnessService_WatchConfigServer interface {
	Send(*ConfigRevision) error
	grpc.ServerStream
}

type endpointHarnessServiceWatchConfigServer struct {
	grpc.ServerStream
}

func (x *endpointHarnessServiceWatchConfigServer) Send(m *ConfigRevision) error {
	return x.ServerStream.SendMsg(m)
}

func _EndpointHarnessService_AckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HarnessAckConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointHarnessServiceServer).AckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointHarnessService_AckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointHarnessServiceServer).AckConfig(ctx, req.(*HarnessAckConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointHarnessService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HarnessHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointHarnessServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointHarnessService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointHarnessServiceServer).Heartbeat(ctx, req.(*HarnessHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointHarnessService_PublishEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HarnessPublishEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointHarnessServiceServer).PublishEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointHarnessService_PublishEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointHarnessServiceServer).PublishEvents(ctx, req.(*HarnessPublishEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndpointHarnessService_ServiceDesc is the grpc.ServiceDesc for EndpointHarnessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointHarnessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "managedendpoint.EndpointHarnessService",
	HandlerType: (*EndpointHarnessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _EndpointHarnessService_Register_Handler,
		},
		{
			MethodName: "AckConfig",
			Handler:    _EndpointHarnessService_AckConfig_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _EndpointHarnessService_Heartbeat_Handler,
		},
		{
			MethodName: "PublishEvents",
			Handler:    _EndpointHarnessService_PublishEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfig",
			Handler:       _EndpointHarnessService_WatchConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "managedendpoint.proto",
}

const (
	EndpointAdminService_ListEndpoints_FullMethodName       = "/managedendpoint.EndpointAdminService/ListEndpoints"
	EndpointAdminService_GetEndpoint_FullMethodName         = "/managedendpoint.EndpointAdminService/GetEndpoint"
	EndpointAdminService_ListReplicas_FullMethodName        = "/managedendpoint.EndpointAdminService/ListReplicas"
	EndpointAdminService_GetMetrics_FullMethodName          = "/managedendpoint.EndpointAdminService/GetMetrics"
	EndpointAdminService_GetConfig_FullMethodName           = "/managedendpoint.EndpointAdminService/GetConfig"
	EndpointAdminService_ListConfigRevisions_FullMethodName = "/managedendpoint.EndpointAdminService/ListConfigRevisions"
	EndpointAdminService_PromoteRollout_FullMethodName      = "/managedendpoint.EndpointAdminService/PromoteRollout"
	EndpointAdminService_RollbackRollout_FullMethodName     = "/managedendpoint.EndpointAdminService/RollbackRollout"
	EndpointAdminService_PinVersion_FullMethodName          = "/managedendpoint.EndpointAdminService/PinVersion"
	EndpointAdminService_GetGitOpsStatus_FullMethodName     = "/managedendpoint.EndpointAdminService/GetGitOpsStatus"
	EndpointAdminService_TriggerGitOpsSync_FullMethodName   = "/managedendpoint.EndpointAdminService/TriggerGitOpsSync"
	EndpointAdminService_SetEndpointEnabled_FullMethodName  = "/managedendpoint.EndpointAdminService/SetEndpointEnabled"
	EndpointAdminService_ListServices_FullMethodName        = "/managedendpoint.EndpointAdminService/ListServices"
	EndpointAdminService_StartTuningReplica_FullMethodName  = "/managedendpoint.EndpointAdminService/StartTuningReplica"
	EndpointAdminService_StopReplica_FullMethodName         = "/managedendpoint.EndpointAdminService/StopReplica"
	EndpointAdminService_SetConfig_FullMethodName           = "/managedendpoint.EndpointAdminService/SetConfig"
)

// EndpointAdminServiceClient is the client API for EndpointAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointAdminServiceClient interface {
	ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error)
	GetEndpoint(ctx context.Context, in *GetEndpointRequest, opts ...grpc.CallOption) (*GetEndpointResponse, error)
	ListReplicas(ctx context.Context, in *ListReplicasRequest, opts ...grpc.CallOption) (*ListReplicasResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	ListConfigRevisions(ctx context.Context, in *ListConfigRevisionsRequest, opts ...grpc.CallOption) (*ListConfigRevisionsResponse, error)
	PromoteRollout(ctx context.Context, in *PromoteRolloutRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error)
	RollbackRollout(ctx context.Context, in *RollbackRolloutRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error)
	PinVersion(ctx context.Context, in *PinVersionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error)
	GetGitOpsStatus(ctx context.Context, in *GetGitOpsStatusRequest, opts ...grpc.CallOption) (*GetGitOpsStatusResponse, error)
	TriggerGitOpsSync(ctx context.Context, in *TriggerGitOpsSyncRequest, opts ...grpc.CallOption) (*TriggerGitOpsSyncResponse, error)
	SetEndpointEnabled(ctx context.Context, in *SetEndpointEnabledRequest, opts ...grpc.CallOption) (*SetEndpointEnabledResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Live tuning. An agent starts a dedicated tuning replica (no public
	// traffic; address it with X-Beam-Endpoint-Replica), pushes replica-scoped
	// configs with SetConfig and reads GetMetrics, then promotes the winner to
	// the fleet with a target-scoped SetConfig and stops the replica.
	StartTuningReplica(ctx context.Context, in *StartTuningReplicaRequest, opts ...grpc.CallOption) (*ReplicaResponse, error)
	StopReplica(ctx context.Context, in *StopReplicaRequest, opts ...grpc.CallOption) (*ReplicaResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
}

type endpointAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointAdminServiceClient(cc grpc.ClientConnInterface) EndpointAdminServiceClient {
	return &endpointAdminServiceClient{cc}
}

func (c *endpointAdminServiceClient) ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error) {
	out := new(ListEndpointsResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_ListEndpoints_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) GetEndpoint(ctx context.Context, in *GetEndpointRequest, opts ...grpc.CallOption) (*GetEndpointResponse, error) {
	out := new(GetEndpointResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_GetEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) ListReplicas(ctx context.Context, in *ListReplicasRequest, opts ...grpc.CallOption) (*ListReplicasResponse, error) {
	out := new(ListReplicasResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_ListReplicas_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_GetMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_GetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) ListConfigRevisions(ctx context.Context, in *ListConfigRevisionsRequest, opts ...grpc.CallOption) (*ListConfigRevisionsResponse, error) {
	out := new(ListConfigRevisionsResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_ListConfigRevisions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) PromoteRollout(ctx context.Context, in *PromoteRolloutRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error) {
	out := new(RolloutActionResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_PromoteRollout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) RollbackRollout(ctx context.Context, in *RollbackRolloutRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error) {
	out := new(RolloutActionResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_RollbackRollout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) PinVersion(ctx context.Context, in *PinVersionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error) {
	out := new(RolloutActionResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_PinVersion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) GetGitOpsStatus(ctx context.Context, in *GetGitOpsStatusRequest, opts ...grpc.CallOption) (*GetGitOpsStatusResponse, error) {
	out := new(GetGitOpsStatusResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_GetGitOpsStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) TriggerGitOpsSync(ctx context.Context, in *TriggerGitOpsSyncRequest, opts ...grpc.CallOption) (*TriggerGitOpsSyncResponse, error) {
	out := new(TriggerGitOpsSyncResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_TriggerGitOpsSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) SetEndpointEnabled(ctx context.Context, in *SetEndpointEnabledRequest, opts ...grpc.CallOption) (*SetEndpointEnabledResponse, error) {
	out := new(SetEndpointEnabledResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_SetEndpointEnabled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_ListServices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) StartTuningReplica(ctx context.Context, in *StartTuningReplicaRequest, opts ...grpc.CallOption) (*ReplicaResponse, error) {
	out := new(ReplicaResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_StartTuningReplica_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) StopReplica(ctx context.Context, in *StopReplicaRequest, opts ...grpc.CallOption) (*ReplicaResponse, error) {
	out := new(ReplicaResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_StopReplica_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointAdminServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, EndpointAdminService_SetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointAdminServiceServer is the server API for EndpointAdminService service.
// All implementations must embed UnimplementedEndpointAdminServiceServer
// for forward compatibility
type EndpointAdminServiceServer interface {
	ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error)
	GetEndpoint(context.Context, *GetEndpointRequest) (*GetEndpointResponse, error)
	ListReplicas(context.Context, *ListReplicasRequest) (*ListReplicasResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	ListConfigRevisions(context.Context, *ListConfigRevisionsRequest) (*ListConfigRevisionsResponse, error)
	PromoteRollout(context.Context, *PromoteRolloutRequest) (*RolloutActionResponse, error)
	RollbackRollout(context.Context, *RollbackRolloutRequest) (*RolloutActionResponse, error)
	PinVersion(context.Context, *PinVersionRequest) (*RolloutActionResponse, error)
	GetGitOpsStatus(context.Context, *GetGitOpsStatusRequest) (*GetGitOpsStatusResponse, error)
	TriggerGitOpsSync(context.Context, *TriggerGitOpsSyncRequest) (*TriggerGitOpsSyncResponse, error)
	SetEndpointEnabled(context.Context, *SetEndpointEnabledRequest) (*SetEndpointEnabledResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Live tuning. An agent starts a dedicated tuning replica (no public
	// traffic; address it with X-Beam-Endpoint-Replica), pushes replica-scoped
	// configs with SetConfig and reads GetMetrics, then promotes the winner to
	// the fleet with a target-scoped SetConfig and stops the replica.
	StartTuningReplica(context.Context, *StartTuningReplicaRequest) (*ReplicaResponse, error)
	StopReplica(context.Context, *StopReplicaRequest) (*ReplicaResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	mustEmbedUnimplementedEndpointAdminServiceServer()
}

// UnimplementedEndpointAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEndpointAdminServiceServer struct {
}

func (UnimplementedEndpointAdminServiceServer) ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (UnimplementedEndpointAdminServiceServer) GetEndpoint(context.Context, *GetEndpointRequest) (*GetEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndpoint not implemented")
}
func (UnimplementedEndpointAdminServiceServer) ListReplicas(context.Context, *ListReplicasRequest) (*ListReplicasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReplicas not implemented")
}
func (UnimplementedEndpointAdminServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedEndpointAdminServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedEndpointAdminServiceServer) ListConfigRevisions(context.Context, *ListConfigRevisionsRequest) (*ListConfigRevisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigRevisions not implemented")
}
func (UnimplementedEndpointAdminServiceServer) PromoteRollout(context.Context, *PromoteRolloutRequest) (*RolloutActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteRollout not implemented")
}
func (UnimplementedEndpointAdminServiceServer) RollbackRollout(context.Context, *RollbackRolloutRequest) (*RolloutActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackRollout not implemented")
}
func (UnimplementedEndpointAdminServiceServer) PinVersion(context.Context, *PinVersionRequest) (*RolloutActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PinVersion not implemented")
}
func (UnimplementedEndpointAdminServiceServer) GetGitOpsStatus(context.Context, *GetGitOpsStatusRequest) (*GetGitOpsStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitOpsStatus not implemented")
}
func (UnimplementedEndpointAdminServiceServer) TriggerGitOpsSync(context.Context, *TriggerGitOpsSyncRequest) (*TriggerGitOpsSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerGitOpsSync not implemented")
}
func (UnimplementedEndpointAdminServiceServer) SetEndpointEnabled(context.Context, *SetEndpointEnabledRequest) (*SetEndpointEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEndpointEnabled not implemented")
}
func (UnimplementedEndpointAdminServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedEndpointAdminServiceServer) StartTuningReplica(context.Context, *StartTuningReplicaRequest) (*ReplicaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTuningReplica not implemented")
}
func (UnimplementedEndpointAdminServiceServer) StopReplica(context.Context, *StopReplicaRequest) (*ReplicaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopReplica not implemented")
}
func (UnimplementedEndpointAdminServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedEndpointAdminServiceServer) mustEmbedUnimplementedEndpointAdminServiceServer() {}

// UnsafeEndpointAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointAdminServiceServer will
// result in compilation errors.
type UnsafeEndpointAdminServiceServer interface {
	mustEmbedUnimplementedEndpointAdminServiceServer()
}

func RegisterEndpointAdminServiceServer(s grpc.ServiceRegistrar, srv EndpointAdminServiceServer) {
	s.RegisterService(&EndpointAdminService_ServiceDesc, srv)
}

func _EndpointAdminService_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_ListEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).ListEndpoints(ctx, req.(*ListEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_GetEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).GetEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_GetEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).GetEndpoint(ctx, req.(*GetEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_ListReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplicasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).ListReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_ListReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).ListReplicas(ctx, req.(*ListReplicasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_ListConfigRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).ListConfigRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_ListConfigRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).ListConfigRevisions(ctx, req.(*ListConfigRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_PromoteRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).PromoteRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_PromoteRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).PromoteRollout(ctx, req.(*PromoteRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_RollbackRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).RollbackRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_RollbackRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).RollbackRollout(ctx, req.(*RollbackRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_PinVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).PinVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_PinVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).PinVersion(ctx, req.(*PinVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_GetGitOpsStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitOpsStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).GetGitOpsStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_GetGitOpsStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).GetGitOpsStatus(ctx, req.(*GetGitOpsStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_TriggerGitOpsSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerGitOpsSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).TriggerGitOpsSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_TriggerGitOpsSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).TriggerGitOpsSync(ctx, req.(*TriggerGitOpsSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_SetEndpointEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEndpointEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).SetEndpointEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_SetEndpointEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).SetEndpointEnabled(ctx, req.(*SetEndpointEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_StartTuningReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTuningReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).StartTuningReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_StartTuningReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).StartTuningReplica(ctx, req.(*StartTuningReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_StopReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).StopReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_StopReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).StopReplica(ctx, req.(*StopReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointAdminService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointAdminServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointAdminService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointAdminServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndpointAdminService_ServiceDesc is the grpc.ServiceDesc for EndpointAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "managedendpoint.EndpointAdminService",
	HandlerType: (*EndpointAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndpoints",
			Handler:    _EndpointAdminService_ListEndpoints_Handler,
		},
		{
			MethodName: "GetEndpoint",
			Handler:    _EndpointAdminService_GetEndpoint_Handler,
		},
		{
			MethodName: "ListReplicas",
			Handler:    _EndpointAdminService_ListReplicas_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _EndpointAdminService_GetMetrics_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _EndpointAdminService_GetConfig_Handler,
		},
		{
			MethodName: "ListConfigRevisions",
			Handler:    _EndpointAdminService_ListConfigRevisions_Handler,
		},
		{
			MethodName: "PromoteRollout",
			Handler:    _EndpointAdminService_PromoteRollout_Handler,
		},
		{
			MethodName: "RollbackRollout",
			Handler:    _EndpointAdminService_RollbackRollout_Handler,
		},
		{
			MethodName: "PinVersion",
			Handler:    _EndpointAdminService_PinVersion_Handler,
		},
		{
			MethodName: "GetGitOpsStatus",
			Handler:    _EndpointAdminService_GetGitOpsStatus_Handler,
		},
		{
			MethodName: "TriggerGitOpsSync",
			Handler:    _EndpointAdminService_TriggerGitOpsSync_Handler,
		},
		{
			MethodName: "SetEndpointEnabled",
			Handler:    _EndpointAdminService_SetEndpointEnabled_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _EndpointAdminService_ListServices_Handler,
		},
		{
			MethodName: "StartTuningReplica",
			Handler:    _EndpointAdminService_StartTuningReplica_Handler,
		},
		{
			MethodName: "StopReplica",
			Handler:    _EndpointAdminService_StopReplica_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _EndpointAdminService_SetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managedendpoint.proto",
}
