// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: trace_repo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TraceRepositoryService_RecordTraceEvent_FullMethodName = "/TraceRepositoryService/RecordTraceEvent"
	TraceRepositoryService_RecordTraceSpan_FullMethodName  = "/TraceRepositoryService/RecordTraceSpan"
	TraceRepositoryService_RecordTraceLog_FullMethodName   = "/TraceRepositoryService/RecordTraceLog"
)

// TraceRepositoryServiceClient is the client API for TraceRepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceRepositoryServiceClient interface {
	RecordTraceEvent(ctx context.Context, in *RecordTraceEventRequest, opts ...grpc.CallOption) (*RecordTraceEventResponse, error)
	RecordTraceSpan(ctx context.Context, in *RecordTraceSpanRequest, opts ...grpc.CallOption) (*RecordTraceSpanResponse, error)
	RecordTraceLog(ctx context.Context, in *RecordTraceLogRequest, opts ...grpc.CallOption) (*RecordTraceLogResponse, error)
}

type traceRepositoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceRepositoryServiceClient(cc grpc.ClientConnInterface) TraceRepositoryServiceClient {
	return &traceRepositoryServiceClient{cc}
}

func (c *traceRepositoryServiceClient) RecordTraceEvent(ctx context.Context, in *RecordTraceEventRequest, opts ...grpc.CallOption) (*RecordTraceEventResponse, error) {
	out := new(RecordTraceEventResponse)
	err := c.cc.Invoke(ctx, TraceRepositoryService_RecordTraceEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceRepositoryServiceClient) RecordTraceSpan(ctx context.Context, in *RecordTraceSpanRequest, opts ...grpc.CallOption) (*RecordTraceSpanResponse, error) {
	out := new(RecordTraceSpanResponse)
	err := c.cc.Invoke(ctx, TraceRepositoryService_RecordTraceSpan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceRepositoryServiceClient) RecordTraceLog(ctx context.Context, in *RecordTraceLogRequest, opts ...grpc.CallOption) (*RecordTraceLogResponse, error) {
	out := new(RecordTraceLogResponse)
	err := c.cc.Invoke(ctx, TraceRepositoryService_RecordTraceLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceRepositoryServiceServer is the server API for TraceRepositoryService service.
// All implementations must embed UnimplementedTraceRepositoryServiceServer
// for forward compatibility
type TraceRepositoryServiceServer interface {
	RecordTraceEvent(context.Context, *RecordTraceEventRequest) (*RecordTraceEventResponse, error)
	RecordTraceSpan(context.Context, *RecordTraceSpanRequest) (*RecordTraceSpanResponse, error)
	RecordTraceLog(context.Context, *RecordTraceLogRequest) (*RecordTraceLogResponse, error)
	mustEmbedUnimplementedTraceRepositoryServiceServer()
}

// UnimplementedTraceRepositoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTraceRepositoryServiceServer struct {
}

func (UnimplementedTraceRepositoryServiceServer) RecordTraceEvent(context.Context, *RecordTraceEventRequest) (*RecordTraceEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordTraceEvent not implemented")
}
func (UnimplementedTraceRepositoryServiceServer) RecordTraceSpan(context.Context, *RecordTraceSpanRequest) (*RecordTraceSpanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordTraceSpan not implemented")
}
func (UnimplementedTraceRepositoryServiceServer) RecordTraceLog(context.Context, *RecordTraceLogRequest) (*RecordTraceLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordTraceLog not implemented")
}
func (UnimplementedTraceRepositoryServiceServer) mustEmbedUnimplementedTraceRepositoryServiceServer() {
}

// UnsafeTraceRepositoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceRepositoryServiceServer will
// result in compilation errors.
type UnsafeTraceRepositoryServiceServer interface {
	mustEmbedUnimplementedTraceRepositoryServiceServer()
}

func RegisterTraceRepositoryServiceServer(s grpc.ServiceRegistrar, srv TraceRepositoryServiceServer) {
	s.RegisterService(&TraceRepositoryService_ServiceDesc, srv)
}

func _TraceRepositoryService_RecordTraceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordTraceEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceRepositoryServiceServer).RecordTraceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceRepositoryService_RecordTraceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceRepositoryServiceServer).RecordTraceEvent(ctx, req.(*RecordTraceEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceRepositoryService_RecordTraceSpan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordTraceSpanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceRepositoryServiceServer).RecordTraceSpan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceRepositoryService_RecordTraceSpan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceRepositoryServiceServer).RecordTraceSpan(ctx, req.(*RecordTraceSpanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceRepositoryService_RecordTraceLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordTraceLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceRepositoryServiceServer).RecordTraceLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceRepositoryService_RecordTraceLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceRepositoryServiceServer).RecordTraceLog(ctx, req.(*RecordTraceLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TraceRepositoryService_ServiceDesc is the grpc.ServiceDesc for TraceRepositoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraceRepositoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TraceRepositoryService",
	HandlerType: (*TraceRepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordTraceEvent",
			Handler:    _TraceRepositoryService_RecordTraceEvent_Handler,
		},
		{
			MethodName: "RecordTraceSpan",
			Handler:    _TraceRepositoryService_RecordTraceSpan_Handler,
		},
		{
			MethodName: "RecordTraceLog",
			Handler:    _TraceRepositoryService_RecordTraceLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trace_repo.proto",
}
