// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: worker_pool_repo.proto

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// WorkerPoolRepositoryServiceClient is the client API for WorkerPoolRepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerPoolRepositoryServiceClient interface {
}

type workerPoolRepositoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerPoolRepositoryServiceClient(cc grpc.ClientConnInterface) WorkerPoolRepositoryServiceClient {
	return &workerPoolRepositoryServiceClient{cc}
}

// WorkerPoolRepositoryServiceServer is the server API for WorkerPoolRepositoryService service.
// All implementations must embed UnimplementedWorkerPoolRepositoryServiceServer
// for forward compatibility
type WorkerPoolRepositoryServiceServer interface {
	mustEmbedUnimplementedWorkerPoolRepositoryServiceServer()
}

// UnimplementedWorkerPoolRepositoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerPoolRepositoryServiceServer struct {
}

func (UnimplementedWorkerPoolRepositoryServiceServer) mustEmbedUnimplementedWorkerPoolRepositoryServiceServer() {
}

// UnsafeWorkerPoolRepositoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerPoolRepositoryServiceServer will
// result in compilation errors.
type UnsafeWorkerPoolRepositoryServiceServer interface {
	mustEmbedUnimplementedWorkerPoolRepositoryServiceServer()
}

func RegisterWorkerPoolRepositoryServiceServer(s grpc.ServiceRegistrar, srv WorkerPoolRepositoryServiceServer) {
	s.RegisterService(&WorkerPoolRepositoryService_ServiceDesc, srv)
}

// WorkerPoolRepositoryService_ServiceDesc is the grpc.ServiceDesc for WorkerPoolRepositoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerPoolRepositoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WorkerPoolRepositoryService",
	HandlerType: (*WorkerPoolRepositoryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "worker_pool_repo.proto",
}
