worker:
  pools:
    default:
      containerStartConcurrency: 128
      jobSpec:
        env:
        - name: CONFIG_PATH
          value: /etc/beta9/.config.yaml
        volumes:
        - name: config
          secret:
            secretName: beta9-config
        volumeMounts:
        - mountPath: /etc/beta9
          name: config
monitoring:
  fluentbit:
    events:
      endpoint: http://fluent-bit.monitoring:9880
cache:
  requiredContent:
    enabled: false
    stubTTL: 168h
    volumeMinBytes: 33554432
    reconcileInterval: 30s
    reconcileConcurrency: 2
    batchSize: 256
    maxBytesPerCycle: 34359738368
    originFallbackEnabled: true
  server:
    pageSizeBytes: 4194304
