worker:
  pools:
    default:
      containerStartConcurrency: 128
      jobSpec:
        env:
        - name: CONFIG_PATH
          value: /etc/beta9/.config.yaml
        volumes:
        - name: config
          secret:
            secretName: beta9-config
        volumeMounts:
        - mountPath: /etc/beta9
          name: config
events:
  callbacks:
  - url: ""
    format: beta9_webhook
    headers:
      Authorization: ""
    eventTypes:
    - stub.deploy
    - stub.serve
    - stub.run
    - stub.clone
    - workerpool.degraded
    - workerpool.healthy
    - gateway.endpoint.called
managedCompute:
  billing:
    mode: noop
    endpoint: ""
    authToken: ""
    required: false
    timeout: 5s
    reconcileInterval: 1m
    minimumCreditCents: 2500
cache:
  server:
    pageSizeBytes: 4194304
