---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- persistent-volume-claim.yaml
- secret.yaml
- service-account.yaml
- service.yaml

generators:
- secret-generator.yaml

components:
- ./juicefs
- ./redis
- ./postgresql
