---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
- pairs:
    app.kubernetes.io/name: beta9
  includeSelectors: true
  includeTemplates: true
- pairs:
    app.kubernetes.io/managed-by: kustomize

resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- persistent-volume-claim.yaml
- secret.yaml
- service-account.yaml
- service.yaml

generators:
- secret-generator.yaml
