---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beta9-images
  namespace: beta9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
