---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: beta9
  name: gateway
  namespace: beta9
secrets:
- name: gateway-sa-token
