apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workerpools.beam.cloud
spec:
  group: beam.cloud
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              jobSpec:
                type: object
                properties:
                  nodeSelector:
                    type: object
                    additionalProperties:
                      type: string
  names:
    kind: WorkerPool
    plural: workerpools
    singular: workerpool
    shortNames:
    - wp
  scope: Namespaced
