# fly.toml app configuration file generated for beam-headscale-test on 2024-01-30T10:03:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'control-plane-headscale'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[build]

[processes]
  headscale = 'serve'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['headscale']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['headscale']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 2048
  processes = ['headscale']
