---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &name localstack
releaseName: *name
name: localstack
repo: https://localstack.github.io/helm-charts
version: 0.6.8
namespace: beta9
includeCRDs: true
skipTests: true
valuesInline:
  extraEnvVars:
  - name: SERVICES
    value: s3
  enableStartupScripts: true
  startupScriptContent: |
    #!/bin/bash
    awslocal s3 mb s3://juicefs
    awslocal s3 mb s3://logs
  persistence:
    enabled: true
    storageClass: local-path
    accessModes:
    - ReadWriteOnce
    size: 50Gi
