import hashlib
import json
import os
import tempfile
import threading
import zipfile
from http import HTTPStatus
from pathlib import Path
from queue import Queue
from typing import Dict, Generator, List, NamedTuple, Optional

import requests
from watchdog.events import FileSystemEvent, FileSystemEventHandler

from beta9.vendor.pathspec import PathSpec

from . import terminal
from .clients.gateway import (
    CommitObjectDeltaRequest,
    CommitObjectDeltaResponse,
    CreateObjectDeltaRequest,
    CreateObjectDeltaResponse,
    CreateObjectRequest,
    CreateObjectResponse,
    GatewayServiceStub,
    HeadObjectRequest,
    HeadObjectResponse,
    ObjectMetadata,
    PutObjectRequest,
    SyncContainerWorkspaceOperation,
)
from .config import get_settings
from .env import is_local, is_notebook_env

_sync_lock = threading.Lock()

# Global workspace object id to signal to any other threads that the workspace has already been synced
_workspace_object_id = ""


def set_workspace_object_id(object_id: str) -> None:
    global _workspace_object_id
    _workspace_object_id = object_id


def get_workspace_object_id() -> str:
    global _workspace_object_id
    if not _workspace_object_id:
        _workspace_object_id = ""
    return _workspace_object_id


CHUNK_SIZE = 1024 * 1024 * 4


def ignore_file_name() -> str:
    return f".{get_settings().name}ignore".lower()


def ignore_file_contents() -> str:
    return f"""# Generated by {get_settings().name} SDK
.{get_settings().name.lower()}ignore
.git
.idea
.python-version
.vscode
.venv
venv
__pycache__
.DS_Store
.config
drive/MyDrive
.coverage
.pytest_cache
.ipynb
.ruff_cache
.dockerignore
.ipynb_checkpoints
.env.local
.envrc
**/__pycache__/
**/.pytest_cache/
**/node_modules/
**/.venv/
*.pyc
.next/
.circleci
"""


class FileSyncResult(NamedTuple):
    success: bool = False
    object_id: str = ""


class FileSyncer:
    def __init__(
        self,
        gateway_stub: GatewayServiceStub,
        root_dir=".",
    ):
        self.root_dir = Path(root_dir).absolute()
        self.gateway_stub: GatewayServiceStub = gateway_stub
        self.is_workspace_dir = root_dir == "."

    @property
    def ignore_file_path(self) -> Path:
        return self.root_dir / ignore_file_name()

    def _init_ignore_file(self) -> None:
        if not is_local():
            return

        if self.ignore_file_path.exists():
            return

        terminal.detail(f"Writing {ignore_file_name()} file")
        with self.ignore_file_path.open(mode="w") as f:
            f.writelines(ignore_file_contents())

    def _read_ignore_file(self) -> list:
        if not is_local():
            return []

        terminal.detail(f"Reading {ignore_file_name()} file")

        patterns = []

        if self.ignore_file_path.is_file():
            with self.ignore_file_path.open() as file:
                patterns = [line.strip() for line in file.readlines() if line.strip()]

        return patterns

    def _should_ignore(self, path: str) -> bool:
        relative_path = os.path.relpath(path, self.root_dir)
        spec = getattr(self, "_ignore_spec", None) or PathSpec.from_lines(
            "gitwildmatch", self.ignore_patterns
        )
        return spec.match_file(relative_path)

    def _should_include(self, path: str) -> bool:
        if len(self.include_patterns) == 0:
            return True

        relative_path = os.path.relpath(path, self.root_dir)
        spec = getattr(self, "_include_spec", None) or PathSpec.from_lines(
            "gitwildmatch", self.include_patterns
        )
        return spec.match_file(relative_path)

    def _collect_files(self) -> Generator[str, None, None]:
        if self.ignore_patterns == ["*"]:
            return

        terminal.detail(f"Collecting files from {self.root_dir}")

        for root, dirs, files in os.walk(self.root_dir):
            dirs[:] = [d for d in dirs if not self._should_ignore(os.path.join(root, d))]

            for file in files:
                file_path = os.path.join(root, file)
                if not self._should_ignore(file_path) and self._should_include(file_path):
                    yield file_path

    @staticmethod
    def _calculate_sha256(file_path: str, chunk_size: int = CHUNK_SIZE) -> str:
        hasher = hashlib.sha256()
        with open(file_path, "rb") as file:
            while chunk := file.read(chunk_size):
                hasher.update(chunk)
        return hasher.hexdigest()

    def sync(
        self,
        ignore_patterns: List[str] = [],
        include_patterns: List[str] = [],
        cache_object_id: bool = True,
    ) -> FileSyncResult:
        with _sync_lock:
            if self.is_workspace_dir and get_workspace_object_id() != "" and not is_notebook_env():
                terminal.header("Files already synced")
                return FileSyncResult(success=True, object_id=get_workspace_object_id())
            return self._sync(
                ignore_patterns=ignore_patterns,
                include_patterns=include_patterns,
                cache_object_id=cache_object_id,
            )

    def _sync(
        self,
        ignore_patterns: List[str] = [],
        include_patterns: List[str] = [],
        cache_object_id: bool = True,
    ) -> FileSyncResult:
        terminal.header("Syncing files")

        self._init_ignore_file()

        if ignore_patterns is None or len(ignore_patterns) == 0:
            self.ignore_patterns = self._read_ignore_file()
        else:
            self.ignore_patterns = ignore_patterns

        if include_patterns is None or len(include_patterns) == 0:
            self.include_patterns = []
        else:
            self.include_patterns = include_patterns

        self._ignore_spec = PathSpec.from_lines("gitwildmatch", self.ignore_patterns)
        self._include_spec = (
            PathSpec.from_lines("gitwildmatch", self.include_patterns)
            if self.include_patterns
            else None
        )

        cache = _SyncCache.load(self.root_dir, self.include_patterns)
        manifest = self._build_manifest(cache)
        hash = manifest.hash()
        size = manifest.size()

        if ignore_patterns != ["*"]:
            terminal.detail(f"Collected object is {terminal.humanize_memory(size, base=10)}")

        object_id = None
        head_response: HeadObjectResponse = self.gateway_stub.head_object(
            HeadObjectRequest(hash=hash, supports_put_headers=True)
        )
        if head_response.exists and head_response.ok:
            cache.save(head_response.object_id, manifest)
            if self.is_workspace_dir and cache_object_id:
                set_workspace_object_id(head_response.object_id)
            return FileSyncResult(success=True, object_id=head_response.object_id)

        if not head_response.use_workspace_storage:
            object_id = self._upload_stream(manifest, hash, size)
        else:
            if cache.object_id and cache.manifest is not None:
                object_id = self._upload_delta(manifest, hash, size, cache)
            if object_id is None:
                object_id = self._upload_full(manifest, hash, size)

        if object_id is None:
            terminal.error("File sync failed")
            return FileSyncResult(success=False, object_id="")

        cache.save(object_id, manifest)
        if self.is_workspace_dir and cache_object_id:
            set_workspace_object_id(object_id)
        return FileSyncResult(success=True, object_id=object_id)

    def _build_manifest(self, cache: "_SyncCache") -> "_Manifest":
        """Hash every file to sync, reusing cached hashes for files whose size
        and mtime are unchanged since the last sync of this directory."""
        entries: Dict[str, _ManifestEntry] = {}
        previous = cache.manifest.entries if cache.manifest is not None else {}
        for file in self._collect_files():
            rel = os.path.relpath(file, self.root_dir)
            try:
                st = os.stat(file)
            except OSError as e:
                terminal.warn(f"Failed to add {file}: {e}")
                continue
            mode = st.st_mode & 0o777
            prev = previous.get(rel)
            if prev is not None and prev.size == st.st_size and prev.mtime_ns == st.st_mtime_ns:
                sha = prev.sha256
            else:
                try:
                    sha = self._calculate_sha256(file)
                except OSError as e:
                    terminal.warn(f"Failed to add {file}: {e}")
                    continue
            entries[rel] = _ManifestEntry(
                size=st.st_size, mtime_ns=st.st_mtime_ns, sha256=sha, mode=mode
            )
            terminal.detail(f"Added {file}")
        return _Manifest(entries)

    def _write_archive(self, paths: List[str]) -> str:
        temp_zip_name = tempfile.NamedTemporaryFile(delete=False).name
        with zipfile.ZipFile(temp_zip_name, "w") as zipf:
            for rel in paths:
                try:
                    zipf.write(self.root_dir / rel, rel)
                except OSError as e:
                    terminal.warn(f"Failed to add {rel}: {e}")
        return temp_zip_name

    @staticmethod
    def _put_archive(
        temp_zip_name: str, presigned_url: str, headers: Optional[Dict[str, str]]
    ) -> bool:
        with terminal.progress_open(temp_zip_name, "rb", description=None) as file:
            response = requests.put(presigned_url, data=file, headers=headers or {})
        return response.status_code == HTTPStatus.OK

    def _upload_full(self, manifest: "_Manifest", hash: str, size: int) -> Optional[str]:
        temp_zip_name = self._write_archive(sorted(manifest.entries))
        try:
            terminal.header("Uploading")
            create_object_response: CreateObjectResponse = self.gateway_stub.create_object(
                CreateObjectRequest(
                    object_metadata=ObjectMetadata(name=hash, size=size),
                    hash=hash,
                    size=size,
                    overwrite=True,
                    supports_put_headers=True,
                )
            )
            if not create_object_response.ok:
                terminal.error("File sync failed")
                return None
            if not self._put_archive(
                temp_zip_name,
                create_object_response.presigned_url,
                create_object_response.put_headers,
            ):
                terminal.error("File sync failed")
                return None
            return create_object_response.object_id
        finally:
            os.remove(temp_zip_name)

    def _upload_delta(
        self, manifest: "_Manifest", hash: str, size: int, cache: "_SyncCache"
    ) -> Optional[str]:
        """Upload only the files that changed since the last sync and have the
        gateway merge them into the previous object's archive. Returns None
        when a full upload is the better (or only) option."""
        base = cache.manifest
        changed = [
            rel
            for rel, entry in manifest.entries.items()
            if rel not in base.entries
            or base.entries[rel].sha256 != entry.sha256
            or base.entries[rel].mode != entry.mode
        ]
        removed = [rel for rel in base.entries if rel not in manifest.entries]
        delta_size = sum(manifest.entries[rel].size for rel in changed)
        # Past about half the archive, the merge on the gateway costs more than it saves.
        if size > 0 and delta_size * 2 > size:
            return None

        temp_zip_name = self._write_archive(sorted(changed))
        try:
            terminal.header("Uploading")
            terminal.detail(
                f"Uploading {len(changed)} changed file(s) ({terminal.humanize_memory(delta_size, base=10)}), "
                f"{len(removed)} removed"
            )
            create_response: CreateObjectDeltaResponse = self.gateway_stub.create_object_delta(
                CreateObjectDeltaRequest(
                    hash=hash,
                    size=size,
                    base_object_id=cache.object_id,
                    delta_size=os.path.getsize(temp_zip_name),
                )
            )
            if not create_response.ok:
                if create_response.base_missing:
                    terminal.detail("Previous sync is gone from the server; uploading everything")
                return None
            if not self._put_archive(
                temp_zip_name, create_response.presigned_url, create_response.put_headers
            ):
                return None
            commit_response: CommitObjectDeltaResponse = self.gateway_stub.commit_object_delta(
                CommitObjectDeltaRequest(
                    object_id=create_response.object_id,
                    base_object_id=cache.object_id,
                    removed_paths=removed,
                )
            )
            if not commit_response.ok:
                terminal.detail(
                    f"Incremental sync failed ({commit_response.error_msg}); uploading everything"
                )
                return None
            return commit_response.object_id
        finally:
            os.remove(temp_zip_name)

    def _upload_stream(self, manifest: "_Manifest", hash: str, size: int) -> Optional[str]:
        # TODO: remove this once all workspaces are migrated to use workspace storage
        temp_zip_name = self._write_archive(sorted(manifest.entries))
        metadata = ObjectMetadata(name=hash, size=size)

        def stream_requests():
            with terminal.progress_open(temp_zip_name, "rb", description=None) as file:
                while chunk := file.read(CHUNK_SIZE):
                    yield PutObjectRequest(chunk, metadata, hash, False)

        try:
            terminal.header("Uploading")
            put_response = self.gateway_stub.put_object_stream(stream_requests())
            if put_response.ok:
                return put_response.object_id
            terminal.error("File sync failed")
            return None
        finally:
            os.remove(temp_zip_name)


class _ManifestEntry(NamedTuple):
    size: int
    mtime_ns: int
    sha256: str
    mode: int


class _Manifest:
    """What a sync consists of: every file's path, content hash and mode. Its
    hash identifies the resulting object, so two directories with the same
    content map to the same object regardless of how the archive was built."""

    def __init__(self, entries: Dict[str, _ManifestEntry]):
        self.entries = entries

    def hash(self) -> str:
        hasher = hashlib.sha256()
        for rel in sorted(self.entries):
            e = self.entries[rel]
            hasher.update(f"{rel}\0{e.sha256}\0{e.mode:o}\n".encode())
        return hasher.hexdigest()

    def size(self) -> int:
        return sum(e.size for e in self.entries.values())

    def to_json(self) -> dict:
        return {rel: [e.size, e.mtime_ns, e.sha256, e.mode] for rel, e in self.entries.items()}

    @classmethod
    def from_json(cls, data: dict) -> "_Manifest":
        return cls(
            {
                rel: _ManifestEntry(int(v[0]), int(v[1]), str(v[2]), int(v[3]))
                for rel, v in data.items()
            }
        )


class _SyncCache:
    """Per-directory record of the last synced object and its manifest, kept in
    the SDK config directory. Lets the next sync skip hashing unchanged files
    and upload only the delta."""

    VERSION = 1

    def __init__(self, path: Path, object_id: str = "", manifest: Optional[_Manifest] = None):
        self.path = path
        self.object_id = object_id
        self.manifest = manifest

    @classmethod
    def cache_dir(cls) -> Path:
        return get_settings().config_path.parent / "sync"

    @classmethod
    def load(cls, root_dir: Path, include_patterns: List[str]) -> "_SyncCache":
        key = hashlib.sha256(f"{root_dir}\0{'|'.join(include_patterns)}".encode()).hexdigest()[:32]
        path = cls.cache_dir() / f"{key}.json"
        try:
            with path.open() as f:
                data = json.load(f)
            if data.get("version") == cls.VERSION and data.get("object_id"):
                return cls(path, data["object_id"], _Manifest.from_json(data["manifest"]))
        except (OSError, ValueError, KeyError, TypeError, IndexError):
            pass
        return cls(path)

    def save(self, object_id: str, manifest: _Manifest) -> None:
        self.object_id = object_id
        self.manifest = manifest
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self.path.with_suffix(".tmp")
            with tmp.open("w") as f:
                json.dump(
                    {
                        "version": self.VERSION,
                        "object_id": object_id,
                        "manifest": manifest.to_json(),
                    },
                    f,
                )
            os.replace(tmp, self.path)
        except OSError:
            pass


class SyncEventHandler(FileSystemEventHandler):
    def __init__(self, queue: Queue, hide_logs: bool = False):
        super().__init__()
        self.queue = queue
        self.hide_logs = hide_logs

    def on_any_event(self, event: FileSystemEvent) -> None:
        if not event.is_directory and event.src_path.endswith(".py"):
            if not self.hide_logs:
                terminal.warn(f"Detected changes in '{event.src_path}'. Reloading...")

    def on_created(self, event) -> None:
        self.queue.put((SyncContainerWorkspaceOperation.WRITE, event.src_path, None))

    def on_modified(self, event: FileSystemEvent) -> None:
        self.on_created(event)

    def on_deleted(self, event: FileSystemEvent) -> None:
        self.queue.put((SyncContainerWorkspaceOperation.DELETE, event.src_path, None))

    def on_moved(self, event: FileSystemEvent) -> None:
        self.queue.put((SyncContainerWorkspaceOperation.MOVED, event.src_path, event.dest_path))
