name: Build and release Custom Runner Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build_and_release_runner:
    environment: Release
    name: build (${{ matrix.image }}, ${{ matrix.architecture.platform }})
    runs-on: ${{ matrix.architecture.runner }}
    strategy:
      fail-fast: false
      matrix:
        image: ['py38', 'py39', 'py310', 'py311', 'py312']
        architecture:
          - platform: linux/amd64
            arch: amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          mask-password: 'true'
          registry-type: public

      - name: Build and push Docker image for ${{ matrix.image }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.runner
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/beta9-runner:${{ matrix.image }}-${{ inputs.tag }}-${{ matrix.architecture.arch }}
          target: ${{ matrix.image }}
          platforms: ${{ matrix.architecture.platform }}
          load: false

  publish_runner_manifests:
    needs: build_and_release_runner
    environment: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['py38', 'py39', 'py310', 'py311', 'py312']

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          mask-password: 'true'
          registry-type: public

      - name: Publish multi-platform image manifest
        env:
          IMAGE: ${{ secrets.ECR_REGISTRY }}/beta9-runner
          IMAGE_TAG: ${{ matrix.image }}-${{ inputs.tag }}
        run: |
          docker buildx imagetools create \
            --tag "${IMAGE}:${IMAGE_TAG}" \
            "${IMAGE}:${IMAGE_TAG}-amd64" \
            "${IMAGE}:${IMAGE_TAG}-arm64"
