name: Build and push Chart

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      chart_version:
        description: Version of the Helm Chart
        required: true
        type: string

jobs:
  build_and_push_chart:
    environment: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          mask-password: 'true'
          registry-type: public

      - name: Package and push helm chart to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REGISTRY_ALIAS: n4e0e1y0
          REPOSITORY: beta9-chart
        run: |
          cd ./deploy/charts
          helm package beta9 --dependency-update --version ${{ inputs.chart_version }}
          helm push $REPOSITORY-${{ inputs.chart_version }}.tgz oci://$REGISTRY
