name: Build and Push Worker

on:
  release:
    types: [created]
    tags:
      - 'worker-*'

jobs:
  build_and_release_worker:
    environment: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          mask-password: 'true'
          registry-type: public

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/worker-}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.worker
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/beta9-worker:${{ env.TAG_NAME }}
          build-args: --target=release
          load: false
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: ${{ steps.login-ecr.outputs.registry }}/beta9-worker
          add_git_labels: true
          tag_with_ref: true
