name: Build and Push Gateway

on:
  release:
    types: [created]
    tags:
      - 'gateway-*'

jobs:
  build_and_release_gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/gateway-}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.gateway
          push: true
          tags: ${{ secrets.ECR_REPOSITORY_URL }}/beta9-gateway:${{ env.TAG_NAME }}
          build-args: --target=release
          load: false