name: Build and release Gateway

on:
  release:
    types: [created]

permissions:
  id-token: write

jobs:
  build_and_release_gateway:
    if: startsWith(github.ref, 'refs/tags/gateway-')
    environment: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: v3.14.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_GITHUB }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        with:
          registry-type: public
          mask-password: 'true'

      - name: Build and push container image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile.gateway
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/beta9-gateway:${{ github.ref_name }}
            ${{ steps.login-ecr.outputs.registry }}/beta9-gateway:latest
          target: release
          platforms: linux/amd64,linux/arm64

      - name: Package and push Helm chart to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REGISTRY_ALIAS: n4e0e1y0
          REPOSITORY: beta9-chart
        run: |
          cd deploy/charts
          helm package ./beta9 --dependency-update --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
          helm push $REPOSITORY-${{ github.ref_name }}.tgz oci://$REGISTRY
