# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: disk.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpc
from betterproto.grpcstub.grpcio_client import SyncServiceStub
from betterproto.grpcstub.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpcstub.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class DiskInstance(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    size: str = betterproto.string_field(3)
    mount_path: str = betterproto.string_field(4)
    created_at: datetime = betterproto.message_field(5)
    updated_at: datetime = betterproto.message_field(6)
    workspace_id: str = betterproto.string_field(7)
    workspace_name: str = betterproto.string_field(8)


@dataclass(eq=False, repr=False)
class GetOrCreateDiskRequest(betterproto.Message):
    name: str = betterproto.string_field(1)
    size: str = betterproto.string_field(2)
    mount_path: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class GetOrCreateDiskResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    err_msg: str = betterproto.string_field(2)
    disk: "DiskInstance" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ListDisksRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListDisksResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    err_msg: str = betterproto.string_field(2)
    disks: List["DiskInstance"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class DeleteDiskRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DeleteDiskResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)
    err_msg: str = betterproto.string_field(2)


class DiskServiceStub(SyncServiceStub):
    def get_or_create_disk(
        self, get_or_create_disk_request: "GetOrCreateDiskRequest"
    ) -> "GetOrCreateDiskResponse":
        return self._unary_unary(
            "/disk.DiskService/GetOrCreateDisk",
            GetOrCreateDiskRequest,
            GetOrCreateDiskResponse,
        )(get_or_create_disk_request)

    def list_disks(self, list_disks_request: "ListDisksRequest") -> "ListDisksResponse":
        return self._unary_unary(
            "/disk.DiskService/ListDisks",
            ListDisksRequest,
            ListDisksResponse,
        )(list_disks_request)

    def delete_disk(
        self, delete_disk_request: "DeleteDiskRequest"
    ) -> "DeleteDiskResponse":
        return self._unary_unary(
            "/disk.DiskService/DeleteDisk",
            DeleteDiskRequest,
            DeleteDiskResponse,
        )(delete_disk_request)
