---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: elasticsearch
name: elasticsearch
releaseName: elasticsearch
repo: https://charts.bitnami.com/bitnami
version: 21.3.1
namespace: monitoring
includeCRDs: true
valuesInline:
  image:
    registry: docker.io
    repository: bitnamilegacy/elasticsearch
    tag: 9.1.2-debian-12-r0
  global:
    kibanaEnabled: true
  sysctlImage:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: 12-debian-12-r51
  kibana:
    image:
      registry: docker.io
      repository: bitnamilegacy/kibana
      tag: 9.1.2-debian-12-r0
  master:
    masterOnly: false
    replicaCount: 1
    extraRoles:
    - data
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
